apiVersion: v1
kind: Service
metadata:
  name: {{ include "gart.fullname" . }}-gie-frontend-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: gie-frontend
spec:
  type: ClusterIP
  selector:
    app: gie-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.gie_frontend.gremlinPort }}
      targetPort: gremlin
      nodePort: null