apiVersion: apps/v1
kind: Deployment
metadata:
  name: debezium-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debezium-connect
  template:
    metadata:
      labels:
        app: debezium-connect
    spec:
      containers:
      - name: debezium-connect
        image: debezium/connect:latest 
        env:
        - name: BOOTSTRAP_SERVERS
          value: "kafka-service:9092"  
        - name: GROUP_ID
          value: "1"
        - name: CONFIG_STORAGE_TOPIC
          value: "debezium-connect-configs"
        - name: OFFSET_STORAGE_TOPIC
          value: "debezium-connect-offsets"
        - name: STATUS_STORAGE_TOPIC
          value: "debezium-connect-status"
        ports:
        - containerPort: 8083  
        volumeMounts:
        - name: debezium-config-volume
          mountPath: /kafka/connect/debezium-config
      volumes:
      - name: debezium-config-volume
        configMap:
          name: debezium-config
