apiVersion: v1
kind: Pod
metadata:
  labels:
    app: etcd
  name: etcd-server
spec:
  containers:
    - command:
        - /usr/local/bin/etcd
        - --name
        - etcd-server
        - --initial-advertise-peer-urls
        - http://127.0.0.1:2380
        - --listen-peer-urls
        - http://0.0.0.0:2380
        - --listen-client-urls
        - http://0.0.0.0:2379
        - --advertise-client-urls
        - http://127.0.0.1:2379
        - --initial-cluster
        - etcd-server=http://127.0.0.1:2380
        - --initial-cluster-state
        - new
      image: quay.io/coreos/etcd:latest
      name: etcd-server
      ports:
        - containerPort: 2379
          name: client
          protocol: TCP
        - containerPort: 2380
          name: server
          protocol: TCP
  restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: etcd-service
spec:
  type: ClusterIP
  ports:
    - name: etcd-service-port
      port: 2379
      #nodePort: 22379
      #protocol: TCP
      targetPort: 2379
  selector:
    app: etcd