apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker1
  namespace: gart
spec:
  selector:  # This selector must match the template labels
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
        id: "1"
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-service:9092"
            - name: KAFKA_CFG_NODE_ID
              value: "1"
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: "zoo1:2181"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
              value: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: gart
  labels:
    name: kafka
spec:
  ports:
    - port: 9092
      name: kafka-port
      protocol: TCP
      targetPort: 9092
  selector:
    app: kafka
  type: ClusterIP