apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: writer-statefulset
  namespace: gart
spec:
  serviceName: "writer"
  replicas: 2
  selector:
    matchLabels:
      app: writer
  template:
    metadata:
      labels:
        app: writer
    spec:
      containers:
      - name: writer
        image: gart-writer:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash", "-c"]
        args:
        - |
          cd /workspace/gart/build &&
          ./gart \
          --db-host ${DB_HOST} \
          --db-port ${DB_PORT} \
          --db-name ${DB_NAME} \
          --db-type ${DB_TYPE} \
          --user ${DB_USER} \
          --password ${DB_PASSWORD} \
          --v6d-sock ${V6D_SOCKET} \
          --v6d-size ${V6D_SIZE} \
          --etcd-endpoint ${ETCD_ENDPOINT} \
          --etcd-prefix ${ETCD_PREFIX} \
          --kafka-server ${KAFKA_SERVER} \
          --subgraph-num ${SUBGRAPH_NUM} \
          --subgraph-id $((${HOSTNAME##*-} + 0)) \
          --enable-bulkload ${ENABLE_BULKLOAD} \
          --rg-from-etcd 1 \
          --k8s-mode yes \
          --role writer &&
          sleep infinity
        env:
          - name: KAFKA_SERVER
            value: "kafka-service:9092"
          - name: DB_HOST
            value: "127.0.0.1"
          - name: DB_PORT
            value: "3306"
          - name: DB_USER
            value: "dbuser"
          - name: DB_PASSWORD
            value: "123456"
          - name: DB_TYPE
            value: "mysql"
          - name: DB_NAME
            value: "ldbc"
          - name: V6D_SOCKET
            value: "/tmp/v6d.sock"
          - name: V6D_SIZE
            value: "750G"
          - name: ETCD_ENDPOINT
            value: "etcd-service:2379"
          - name: ETCD_PREFIX
            value: "gart_meta_"
          - name: SUBGRAPH_NUM
            value: "2"
          - name: ENABLE_BULKLOAD
            value: "1" 
          
        
