apiVersion: v1
kind: Service
metadata:
  name: zoo1
  labels:
    app: zookeeper-1
spec:
  type: ClusterIP
  ports:
    - name: zk-port
      port: 2181
      targetPort: 2181
  selector:
    app: zookeeper-1