{{- $kafka_service_name := .Values.kafka.fullnameOverride }}
{{- $kafka_service_port := int .Values.kafka.service.ports.client }}
{{- $kafka_service := printf "%s:%d" $kafka_service_name $kafka_service_port }}
{{- $kafka_service := quote $kafka_service }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gart.debezium.configmapName" . }}
  namespace: {{ .Release.Namespace }}
data:
  mysql-connector.json: |-
    {
      "name": "debezium-connector-mysql",
      "config": {
        "connector.class": "io.debezium.connector.mysql.MySqlConnector",
        "database.hostname": {{ .Values.dataconfig.dbHost | quote }},
        "database.port": {{ .Values.dataconfig.dbPort | quote }},
        "database.user": {{ .Values.dataconfig.dbUser | quote }},
        "database.password": {{ .Values.dataconfig.dbPassword | quote }},
        "database.include.list": {{ .Values.dataconfig.dbName | quote }},
        {{- if eq (int .Values.dataconfig.enableBulkload) 1 }}
        "snapshot.mode": "initial",
        {{- else }}
        "snapshot.mode": "never",
        {{- end }}
        "database.server.id": "1", 
        "include.schema.changes": "false",
        "tombstones.on.delete": "false",
        "topic.prefix": "fullfillment",
        "schema.history.internal.kafka.topic": "schemahistory.fullfillment",
        "transforms": "Combine,ReplaceField",
        "transforms.Combine.type": "io.debezium.transforms.ByLogicalTableRouter",
        "transforms.Combine.topic.regex": "(.*)",
        "transforms.Combine.topic.replacement": "binlog",
        "transforms.ReplaceField.type": "org.apache.kafka.connect.transforms.ReplaceField$Value",
        "transforms.ReplaceField.exclude": "ts_ms,transaction",
        "key.converter": "org.apache.kafka.connect.json.JsonConverter",
        "value.converter": "org.apache.kafka.connect.json.JsonConverter",
        "key.converter.schemas.enable": "false",
        "value.converter.schemas.enable": "false",
        "database.history.kafka.bootstrap.servers": {{ $kafka_service }},
        "schema.history.internal.kafka.bootstrap.servers": {{ $kafka_service }}
      }
    }
