apiVersion: v1
kind: Service
metadata:
  name: {{ include "gart.debezium.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: debezium-connect
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.debezium.containerPort }}
    targetPort: {{ .Values.debezium.containerPort }}
  selector:
    app: debezium-connect
