from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from flex.server.models.base_model import Model
from flex.server import util


class ChangeGraphVersionRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, version_id=None):  # noqa: E501
        """ChangeGraphVersionRequest - a model defined in OpenAPI

        :param version_id: The version_id of this ChangeGraphVersionRequest.  # noqa: E501
        :type version_id: str
        """
        self.openapi_types = {
            'version_id': str
        }

        self.attribute_map = {
            'version_id': 'version_id'
        }

        self._version_id = version_id

    @classmethod
    def from_dict(cls, dikt) -> 'ChangeGraphVersionRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ChangeGraphVersionRequest of this ChangeGraphVersionRequest.  # noqa: E501
        :rtype: ChangeGraphVersionRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def version_id(self) -> str:
        """Gets the version_id of this ChangeGraphVersionRequest.


        :return: The version_id of this ChangeGraphVersionRequest.
        :rtype: str
        """
        return self._version_id

    @version_id.setter
    def version_id(self, version_id: str):
        """Sets the version_id of this ChangeGraphVersionRequest.


        :param version_id: The version_id of this ChangeGraphVersionRequest.
        :type version_id: str
        """
        if version_id is None:
            raise ValueError("Invalid value for `version_id`, must not be `None`")  # noqa: E501

        self._version_id = version_id
