{{- if not .Values.analyzer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gart.fullname" . }}-gie-executor-service
spec:
  selector:
    app: writer
  ports:
  - name: gaia-rpc
    port: {{ .Values.gie_executor.GAIA_RPC_PORT }}
    targetPort: gaia-rpc
  - name: gaia-engine
    port: {{ .Values.gie_executor.ENGINE_PORT }}
    targetPort: gaia-engine
  - name: http-service
    port: {{ .Values.gie_executor.HTTP_SERVICE_PORT }}
    targetPort: {{ .Values.gie_executor.FLASK_PORT }}
  clusterIP: None

{{- end }}