{{- $debezium_service_name := include "gart.debezium.fullname" . }}
{{- $debezium_service_port := int .Values.debezium.containerPort }}
{{- $debezium_service := printf "%s:%d" $debezium_service_name $debezium_service_port }}

{{- $etcd_service_name := .Values.etcd.fullnameOverride }}
{{- $etcd_service_port := int .Values.etcd.containerPorts.client }}
{{- $etcd_service := printf "%s:%d" $etcd_service_name $etcd_service_port }}

{{- $controller_service_name := include "gart.controller-service.fullname" . }}
{{- $controller_service_port := int .Values.controller.port }}
{{- $controller_service := printf "%s:%d" $controller_service_name $controller_service_port }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gart.configmapName" . }}
  namespace: {{ .Release.Namespace }}
data:
  DB_HOST: {{ .Values.dataconfig.dbHost | quote }}
  DB_PORT: {{ .Values.dataconfig.dbPort | quote }}
  DB_USER: {{ .Values.dataconfig.dbUser | quote }}
  DB_PASSWORD: {{ .Values.dataconfig.dbPassword | quote }}
  DB_TYPE: {{ .Values.dataconfig.dbType | quote }}
  DB_NAME: {{ .Values.dataconfig.dbName | quote }}
  {{- if .Values.dataconfig.v6dSocket }}
  V6D_SOCKET: {{ .Values.dataconfig.v6dSocket | quote }}
  {{- else }}
  V6D_SOCKET: "/tmp/shared/v6d.sock"
  {{- end }}
  {{- if .Values.dataconfig.v6dSize }}
  V6D_SIZE: {{ .Values.dataconfig.v6dSize | quote }}
  {{- else }}
  V6D_SIZE: "750G"
  {{- end }}
  {{- if .Values.dataconfig.etcdPrefix }}
  ETCD_PREFIX: {{ .Values.dataconfig.etcdPrefix | quote }}
  {{- else }}
  ETCD_PREFIX: "gart_meta_"
  {{- end }}
  ENABLE_BULKLOAD: {{ .Values.dataconfig.enableBulkload | quote }}
  SUBGRAPH_NUM: {{ .Values.dataconfig.subgraphNum | quote }}
  DEBEZIUM_SERVICE: {{ $debezium_service | quote }}
  DEBEZIUM_CONNECTOR_NAME: {{ include "gart.debezium.fullname" . | quote }}
  CONTROLLER_FLASK_PORT: {{ .Values.controller.containerPort | quote }}
  GART_CONTROLLER_SERVER: {{ $controller_service | quote }}
  ETCD_SERVICE: {{ $etcd_service | quote }}
  GIE_GREMLIN_PORT: {{ .Values.gie_frontend.gremlinPort | quote }}
  GIE_EXECUTOR_RPC_PORT: {{ .Values.gie_executor.GAIA_RPC_PORT | quote }}
  GIE_EXECUTOR_ENGINE_PORT: {{ .Values.gie_executor.ENGINE_PORT | quote }}
  NAME_SPACE: {{ .Release.Namespace | quote }}
  GREMLIN_SERVICE_NAME: {{ include "gart.fullname" . }}-gie-frontend-service
  {{- if .Values.dataconfig.useSecondsPerEpoch }}
  USE_LOGS_PER_EPOCH: "0"
  {{- else }}
  USE_LOGS_PER_EPOCH: "1"
  {{- end }}
  {{- if .Values.dataconfig.logsPerEpoch }}
  LOGS_PER_EPOCH: {{ .Values.dataconfig.logsPerEpoch | quote }}
  {{- else }}
  LOGS_PER_EPOCH: "10000"
  {{- end }}
  {{- if .Values.dataconfig.secondsPerEpoch }}
  SECONDS_PER_EPOCH: {{ .Values.dataconfig.secondsPerEpoch | quote }}
  {{- else }}
  SECONDS_PER_EPOCH: "60"
  {{- end }}
  {{- if not .Values.dataconfig.useGAE }}
  GIE_EXECUTOR_POD_BASE_NAME: {{ include "gart.writer.fullname" . | quote }}
  GIE_EXECUTOR_POD_SERVICE_NAME: {{ include "gart.fullname" . }}-gie-executor-service
  GIE_EXECUTOR_POD_SERVICE_PORT: {{ .Values.gie_executor.HTTP_SERVICE_PORT | quote }}
  GIE_EXECUTOR_RPC_PORT: {{ .Values.gie_executor.GAIA_RPC_PORT | quote }}
  GIE_EXECUTOR_FLASK_PORT: {{ .Values.gie_executor.FLASK_PORT | quote }}
  GIE_FRONTEND_SERVICE_NAME: {{ include "gart.fullname" . }}-gie-frontend-service
  GIE_FRONTEND_SERVIVE_PORT: {{ .Values.gie_frontend.gremlinPort | quote }}
  {{- end }}

